### ISSUE TITLE
Boss wont start :(

### ISSUE THREAD

**Issue by shootingcharlie8** [coleifer/irc#13]
When i start boss.py it gives me this:

```
Traceback (most recent call last):
  File "C:\Users\Charlie\Downloads\irc-master\irc-master\botnet\boss.py", line 347, in <module>
    options.logfile, options.verbosity)
  File "C:\Python27\lib\site-packages\irckit-0.1.1-py2.7.egg\irc.py", line 51, in __init__
    self.logger = self.get_logger('ircconnection.logger', self.logfile)
  File "C:\Python27\lib\site-packages\irckit-0.1.1-py2.7.egg\irc.py", line 58, in get_logger
    handler = RotatingFileHandler(filename, maxBytes=1024*1024, backupCount=2)
  File "C:\Python27\lib\logging\handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python27\lib\logging\__init__.py", line 901, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "C:\Python27\lib\ntpath.py", line 487, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, int found
>>> 
```

**Comment by coleifer** [comment]
Looks like you're passing an integer into the logfile argument?
