### ISSUE TITLE
Cant start boss.py on debian stable (8.2)

### ISSUE THREAD

**Issue by bartekj** [coleifer/irc#14]
Hi there,
just tried to launch boss on couple server with debian. I did installed all requirements but still I'm getting this:

```
Traceback (most recent call last):
  File "boss.py", line 347, in <module>
    options.logfile, options.verbosity)
  File "/usr/local/lib/python2.7/dist-packages/irckit-0.1.1-py2.7.egg/irc.py", line 51, in __init__
    self.logger = self.get_logger('ircconnection.logger', self.logfile)
  File "/usr/local/lib/python2.7/dist-packages/irckit-0.1.1-py2.7.egg/irc.py", line 58, in get_logger
    handler = RotatingFileHandler(filename, maxBytes=1024*1024, backupCount=2)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 901, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "/usr/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'int' object has no attribute 'startswith'

```

**Comment by coleifer** [comment]
How are you invoking the script?

**Comment by bartekj** [comment]
Same way it is in the documentation, lik this:
```
root@debian:~/irc/botnet# python boss.py -s krakow.irc.pl -p 6667 -n x1 -c f17 -x qwerty -f /tmp/boss.log
...
```
Any ideas what I'm missing?

**Comment by coleifer** [comment]
Only thing I can think is you've got a -f somewhere thats  causing the logfile to be treated as a number...or its just broken which would be odd.

**Comment by honey2792** [comment]
Was this issue resolved?
